DROP TABLE BINCOM_TEST;
CREATE DATABASE BINCOM_TEST;

USE BINCOM_TEST;

DROP TABLE IF EXISTS TODO_LIST;

CREATE TABLE TODO_LIST (
    ID SERIAL PRIMARY KEY,
    TODO_ID VARCHAR NOT NULL,
    LIST VARCHAR(500) NOT NULL,
    FOREIGN KEY(TODO_ID) REFERENCES TODO(TODO)
);

DROP TABLE IF EXISTS TODO;

CREATE TABLE TODO (
    ID SERIAL PRIMARY KEY,
    TODO VARCHAR(200) NOT NULL,

);

-- -- Inserting to the db
-- INSERT INTO TODO_LIST(ID,LIST) VALUE ('ID','LIST')

-- -- Deleting items
-- DELETE FROM TODO_LIST WHERE ID = 'id'

-- -- selecting items
-- SELECT * FROM TODO_LIST